config/routes.rb
Rails.application.routes.draw do

  resources :lineup_players
  resources :positions
  resources :gametypes
  get 'deposits/verify'

  get '/terms' => 'welcome#terms', as: :terms
  get '/accounterror' => 'welcome#account_error', as: :account_error
  get '/requireinfo' => 'welcome#requireInfo', as: :require_info

  get 'contests/upcoming'
  get 'contests/live'
  get 'contests/completed'

  devise_for :users, controllers: {
  sessions: 'user/sessions'
}
  resources :withdrawals
  resources :transactions
  resources :deposits
  resources :notifications
  resources :stream_links, path: :watch
  resources :admin
  resources :notifications
  resources :lineups
  resources :slates
  resources :games
  resources :contests
  resources :teams
  resources :players do
    collection do 
      put 'update_individual'
    end
  end
  root 'welcome#index'

  get 'slates/:id/payout' => 'slates#payout'

  get 'players/:id/clearscore' => 'players#clearscore', :as => :clearscore

  get 'slates/:id/scores' => 'slates#scores'

end

app/models/balance.rb
class Balance < ActiveRecord::Base
end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_many :games
  belongs_to :slate
  has_many :lineups

  before_create do 

  end
end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :slate
end

app/models/gametype.rb
class Gametype < ActiveRecord::Base
end

app/models/lineup.rb
class Lineup < ActiveRecord::Base
  belongs_to :user
end

app/models/lineup_player.rb
class LineupPlayer < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/slate.rb
class Slate < ActiveRecord::Base
end

app/models/stream_link.rb
class StreamLink < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :display_name, uniqueness: true
  validates :display_name, length: { in: 3..16 }
  validates_acceptance_of :terms



  validates_format_of :display_name, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true


  around_create :register_hook

  has_many :withdrawals
  has_many :lineups



# config/routes.rb

end

  private
    def register_hook
      self.permissions = 1
      self.balance = 250.00
      self.total_winnings = 0.00

      yield  # this makes the save happen

        balance = Balance.new(user_id: self.id, amount: 250.00)

        balance.save
    end

app/models/withdrawal.rb
class Withdrawal < ActiveRecord::Base
  belongs_to :user
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]
  before_filter :ensure_admin, only: [:new, :create, :destroy, :edit, :update]

  # GET /contests
  # GET /contests.json
  def index
    c = Array.new
    cons = Array.new

    if current_user.permissions == 2
      @contests = Contest.where(paid_out: false).all
      return
    end

    c += Contest.where('start_time >?', Time.now)

    c.each do |c|
      cons.append(c) if c.max_size != c.curr_size
    end

    @contests = cons.uniq

  end

  def upcoming
    cons = Array.new

    lines = Lineup.where(user_id: current_user.id)
    l = Array.new

    lines.each do |line|
      c = Contest.where(id: line.contest_id).where(paid_out: false).take
      if !c.nil?
        if c.start_time > Time.now
          l.append(line)
          cons.append(c)
        end
      end
    end

    @lineups = l.uniq
    @contests = cons.uniq

  end

  def live
    cons = Array.new

    lines = Lineup.where(user_id: current_user.id)
    l = Array.new

    lines.each do |line|
      c = Contest.find(line.contest_id)
      if c.start_time < Time.now && c.paid_out == false
        l.append(line)
        cons.append(c)
      end
    end

    @lineups = l.uniq
    @contests = cons.uniq
  end

  def completed
    cons = Array.new

    lines = Lineup.where(user_id: current_user.id).all
    l = Array.new

    lines.each do |line|
      c = Contest.where(id: line.contest_id).where(paid_out: true).take
      if !c.nil?
        l.append(line)
        cons.append(c)
      end
    end

    @lineups = l.uniq
    @contests = cons.uniq

  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    @gametype = Gametype.find(@contest.game)
    @positions = Position.where(gametype_id: @gametype.id)
    @num_total_positions = 0

    @games = Game.where(slate_id: @contest.slate_id)
    teams = Array.new
    players = Array.new

    @games.each do |game|
      teams.append(Team.find(game.team_1))
      teams.append(Team.find(game.team_2))

      players += (Player.where(team_id: game.team_1).all)
      players += (Player.where(team_id: game.team_2).all)

    end

    @players = players.uniq
    @teams = teams.uniq


    if @contest.start_time < Time.now
      @lineups = Lineup.where(contest_id: @contest.id)
      @lineups.each do |line|
        calcTotalScore(line)
      end
      @lineups = @lineups.order(total_score: :desc)

    end

  end

  # GET /contests/new
  def new
    @slates = Slate.where("start_time > ?", Time.now)
    @teams = Team.all
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
    @slates = Slate.where("start_time > ?", Time.now)
  end

  # POST /contests
  # POST /contests.json
  def create  
    @contest = Contest.new(contest_params)
    @slate = Slate.find(params[:contest][:slate_id])
    @contest.start_time = @slate.start_time
    @contest.curr_size = 0
    @contest.paid_out = false
    @contest.game = @slate.game

    #RECHECK IF NOT FULL

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end
   

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    if @contest.paid_out == false
      lines = Lineup.where(contest_id: @contest.id)
      if !lines.nil?
        lines.each do |l|
          returnBal = Balance.where(user_id: l.user_id).take
          returnBal.amount += @contest.fee
          returnBal.save

          returnUser = User.find(l.user_id)
          returnUser.balance += @contest.fee
          returnUser.save

          refundTrans = Transaction.new(user_id: l.user_id, amount: @contest.fee, description: "Entry Canceled: Contest ID: #{@contest.id} ")
          refundTrans.save
        end
      end
    end

      #RETURN MONEY TO LINEUP OWNER AND EXIT
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:title, :fee, :start_time, :max_size, :curr_size, :prize_pool, :slate_id, :payment_structure, :game)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/lineups_helper.rb
module LineupsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/slates_helper.rb
module SlatesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :fee %><br>
    <%= f.text_field :fee %>
  </div>
  <div class="field">
    <%= f.label :payment_structure %> <br>
    <%= f.number_field :payment_structure %>    
  </div>
  <div class="field">
    <%= f.label "Slate" %><br>
    <%= collection_select(:contest, :slate_id, @slates, :id, :name, {:prompt => true}) %>
  </div>
  <div class="field">
    <%= f.label :max_size %><br>
    <%= f.number_field :max_size %>
  </div>
  <div class="field">
    <%= f.label :prize_pool %><br>
    <%= f.text_field :prize_pool %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/completed.html.erb
<h2>Completed Contests</h2>

<% @contests.each do |c| %>
	<%= c.title %>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing Contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <th>Contest</th>
    <th>Entry</th>
    <th>Prizes</th>
    <th>Start Time</th>
    <th>Entries</th>
  </thead>

      <tr>
        <td><% if @line %>
        <td><%= link_to 'Edit Entry', edit_lineup_path(@line.id, :contest_id => @line.contest_id)%></td>
        <td><%= link_to 'Cancel Entry', @line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %></td>
      </tr>



    <% @contests.each do |contest| %>
      <tr class="contest-details">
        <td>
          <%= link_to "#{contest.title}", contest %>
        </td>
        <td>
          <%= "$#{number_with_precision(contest.fee, precision: 2)}" %>
        </td>
        <td>
          <%= "$#{number_with_precision(contest.prize_pool, precision: 2)}" %>
        </td>
        <td>
          <% s = (contest.start_time.strftime("%A")) %>
         
          <% s = s[0..2].gsub(/\s\w+\s*$/, '') %>
          
          <%= "#{s} #{contest.start_time.strftime("%l:%M %P")}" %>
        </td>
        <td>
          <%= "#{contest.curr_size} / #{contest.max_size}" %>
        </td>
        <% l = (Lineup.where("user_id" => current_user.id).all) %>

        <% l = l.where("contest_id" => contest.id).first %>
        <td>
          <% if l.nil? %>
            <% if current_user.balance >= contest.fee %>
              <%= link_to 'Enter Contest', new_lineup_path(contest_id: contest.id) %>
            <% end %>
          <% else %>
            <%= link_to 'Edit Entry', edit_lineup_path(l.id, :contest_id => l.contest_id)%>
          <% end %>
        </td> <br>
        <td><% if current_user.permissions == 2 %>
        <td>
          <%= link_to 'Remove Contest', contest, method: :delete, data: { confirm: 'Are you sure?' } %>

    
        </td>
        <% end %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.permissions == 2 %>
  <%= link_to 'New Contest', new_contest_path %>
<% end %>

app/views/contests/live.html.erb
<% if @contests.length == 0 %>
	<h3>No Live Entries!</h3>
<% else %>
	<h3>Live Entries</h3>
	<table>
	  <th>Contest</th>
	  <th>Entry</th>
	  <th>Prizes</th>
	  <th>Start Time</th>
	  <th>Size</th>
	  <th>Entries</th>
	<% @contests.each do |c| %>
	  <tr class="contest-details">
	    <td>
	      <%= link_to "#{c.title}", c %>
	    </td>
	    <td>
	      <%= "$#{number_with_precision(c.fee, precision: 2)}" %>
	    </td>
	    <td>
	      <%= "$#{number_with_precision(c.prize_pool, precision: 2)}" %>
	    </td>
	    <td>
	      <%= (c.start_time).strftime("%m/%d/%Y") %>
	    </td>
	    <td>
	      <%= c.max_size %>
	    </td>
	    <td>
	      <%= c.curr_size %>
	    </td>

	  </tr>

	<% end %>

	</table>
	
<% end %>

app/views/contests/new.html.erb
<h1>New Contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>
<% started = true if @contest.start_time < Time.now %>
<% l = (Lineup.where("user_id" => current_user.id)) %>
<% l = l.where("contest_id" => @contest).take %>
<% entered = true if !l.nil? %>

<table>
  <th>Contest</th>
  <th>Entry</th>
  <th>Prizes</th>
  <th>Start Time</th>
  <th>Size</th>
  <th>Entries</th>

  <tr class="contest-details">
    <td>
      <%= @contest.title %>
    </td>
    <td>
      <%= "$#{number_with_precision(@contest.fee, precision: 2)}" %>
    </td>
    <td>
      <%= "$#{number_with_precision(@contest.prize_pool, precision: 2)}" %>
    </td>
    <td>
      <%= (@contest.start_time).strftime("%m/%d/%Y") %>
    </td>
    <td>
      <%= @contest.max_size %>
    </td>
    <td>
      <%= @contest.curr_size %>
    </td>
  </tr>

</table>

<% if entered %>
  <% if current_user.permissions == 2 && @contest.start_time > Time.now%>
    <%= link_to 'Edit', edit_contest_path(@contest) %>
  <% end %>
  <h3>Your Lineup</h3>

  <table>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    
    <% players = LineupPlayer.where(lineup_id: l.id) %>
    <% players.each do |p| %>
      <% player = Player.find(p.player_id) %>
    <tr class="contest-entries">
      <td><%= @positions.where(pos_num: player.position).take.abbr %></td>
      <td>
        <span><%= player.name %></span>
      </td>
      <td></td>
      <td><%= player.salary %></td>
      <% if started %>
        <td><%= player.live_score %></td>
      <% end %>
    </tr>
    <% end %>

  </table>
<% end %>

<br>


<% if @contest.start_time < Time.now %>
  <br><br>
  <table name = lineups-table, cellspacing="0">
    <th>User</th>
    <th>Score</th>
  <% @lineups.each do |lineup| %>
    <tr class="contest-entries">
      <% user = User.find(lineup.user_id) %>
      <td>
        <%= link_to "#{user.display_name}", lineup_path(lineup.id, :contest_id => @contest.id) %>
        <button class="tester"></button>
      </td>
      <td><%= lineup.total_score %></td>
    </tr>

  <% end %>
  </table>
<% end %>

<h2>Games</h2>
<% @games.each do |game| %>
  <span><%= "#{Team.find(game.team_1).name} vs #{Team.find(game.team_2).name}" %></span>
  <br>
<% end %>
<br>
<% if current_user.permissions == 1 %>
  <% if @contest.start_time > Time.now %>
    <% if !entered %>

      <%= link_to 'Enter Contest', new_lineup_path(contest_id: @contest.id) %> <br>
    <% else %>
      <%= link_to 'Edit Entry', edit_lineup_path(l.id, :contest_id => @contest.id)%>
      <br>
    <% end %>
  <% end %>

<% end %>

app/views/contests/upcoming.html.erb
<h1>Upcoming Contests</h1>

<table>
    <th>Contest</th>
    <th>Entry</th>
    <th>Prizes</th>
    <th>Start Time</th>
    <th>Size</th>
    <th>Total Entries</th>

  <tbody>
    <% @contests.each do |contest| %>
    <% @line = Lineup.where(contest_id: contest.id) %>
    <% @line = @line.where(user_id: current_user.id).take %>
      <tr class="contest-details">
        <td>
          <%= link_to "#{contest.title}", contest %>
        </td>
        <td>
          <%= "$#{number_with_precision(contest.fee, precision: 2)}" %>
        </td>
        <td>
          <%= "$#{number_with_precision(contest.prize_pool, precision: 2)}" %>
        </td>
        <td>
          <%= (contest.start_time).strftime("%m/%d/%Y") %>
        </td>
        <td>
          <%= contest.max_size %>
        </td>
        <td>
          <%= contest.curr_size %>
        </td>

        <td><% if @line %>
        <td><%= link_to 'Edit Entry', edit_lineup_path(@line.id, :contest_id => @line.contest_id)%></td>
        <td><%= link_to 'Cancel Entry', @line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  
  <% @contests.each do |c| %>
    

  <% end %>

  </table>