config/routes.rb
Rails.application.routes.draw do

  resources :lineup_players
  resources :positions
  resources :gametypes
  get 'deposits/verify'

  get '/terms' => 'welcome#terms', as: :terms
  get '/accounterror' => 'welcome#account_error', as: :account_error
  get '/requireinfo' => 'welcome#requireInfo', as: :require_info

  get 'contests/upcoming'
  get 'contests/live'
  get 'contests/completed'

  devise_for :users, controllers: {
  sessions: 'user/sessions'
}
  resources :withdrawals
  resources :transactions
  resources :deposits
  resources :notifications
  resources :stream_links, path: :watch
  resources :admin
  resources :notifications
  resources :lineups
  resources :slates
  resources :games
  resources :contests
  resources :teams
  resources :players do
    collection do 
      put 'update_individual'
    end
  end
  root 'welcome#index'

  get 'slates/:id/payout' => 'slates#payout'

  get 'players/:id/clearscore' => 'players#clearscore', :as => :clearscore

  get 'slates/:id/scores' => 'slates#scores'

end

app/models/balance.rb
class Balance < ActiveRecord::Base
end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_many :games
  belongs_to :slate
  has_many :lineups

  before_create do 

  end
end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :slate
end

app/models/gametype.rb
class Gametype < ActiveRecord::Base
end

app/models/lineup.rb
class Lineup < ActiveRecord::Base
  belongs_to :user
end

app/models/lineup_player.rb
class LineupPlayer < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/slate.rb
class Slate < ActiveRecord::Base
end

app/models/stream_link.rb
class StreamLink < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :display_name, uniqueness: true
  validates :display_name, length: { in: 3..16 }
  validates_acceptance_of :terms



  validates_format_of :display_name, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true


  around_create :register_hook

  has_many :withdrawals
  has_many :lineups



# config/routes.rb

end

  private
    def register_hook
      self.permissions = 1
      self.balance = 250.00
      self.total_winnings = 0.00

      yield  # this makes the save happen

        balance = Balance.new(user_id: self.id, amount: 250.00)

        balance.save
    end

app/models/withdrawal.rb
class Withdrawal < ActiveRecord::Base
  belongs_to :user
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/lineups_helper.rb
module LineupsHelper
end

app/helpers/slates_helper.rb
module SlatesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/admin/index.html.erb
<h1>ADMIN PANEL</h1>
<h3>Gametype</h3>
<%= link_to 'View Gametypes', gametypes_path %>
<br>
<%= link_to 'New Gametype', new_gametype_path %>
<br><br>

<%= link_to 'View Positions', positions_path %>
<br>
<%= link_to 'New Position', new_position_path %>
<br><br>

<h3>Teams</h3>
<%= link_to 'View Teams', teams_path %>
<br>
<%= link_to 'New Team', new_team_path %>
<br><br>

<h3>Players</h3>
<%= link_to 'View Players', players_path %>
<br>
<%= link_to 'New Player', new_player_path %>
<br><br>

<h3>Games</h3>
<%= link_to 'View Games', games_path %>
<br>
<%= link_to 'New Game', new_game_path %>
<br><br>

<h3>Slates</h3>
<%= link_to 'View Slates', slates_path %>
<br>
<%= link_to 'New Slate', new_slate_path %>
<br><br>

<h3>Contests</h3>
<%= link_to 'View Contests', contests_path %>
<br>
<%= link_to 'New Contest', new_contest_path %>
<br><br>