config/routes.rb
Rails.application.routes.draw do

  resources :lineup_players
  resources :positions
  resources :gametypes
  get 'deposits/verify'

  get '/terms' => 'welcome#terms', as: :terms
  get '/accounterror' => 'welcome#account_error', as: :account_error
  get '/requireinfo' => 'welcome#requireInfo', as: :require_info

  get 'contests/upcoming'
  get 'contests/live'
  get 'contests/completed'

  devise_for :users, controllers: {
  sessions: 'user/sessions'
}
  resources :withdrawals
  resources :transactions
  resources :deposits
  resources :notifications
  resources :stream_links, path: :watch
  resources :admin
  resources :notifications
  resources :lineups
  resources :slates
  resources :games
  resources :contests
  resources :teams
  resources :players do
    collection do 
      put 'update_individual'
    end
  end
  root 'welcome#index'

  get 'slates/:id/payout' => 'slates#payout'

  get 'players/:id/clearscore' => 'players#clearscore', :as => :clearscore

  get 'slates/:id/scores' => 'slates#scores'

end

app/models/balance.rb
class Balance < ActiveRecord::Base
end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_many :games
  belongs_to :slate
  has_many :lineups

  before_create do 

  end
end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :slate
end

app/models/gametype.rb
class Gametype < ActiveRecord::Base
end

app/models/lineup.rb
class Lineup < ActiveRecord::Base
  belongs_to :user
end

app/models/lineup_player.rb
class LineupPlayer < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/slate.rb
class Slate < ActiveRecord::Base
end

app/models/stream_link.rb
class StreamLink < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :display_name, uniqueness: true
  validates :display_name, length: { in: 3..16 }
  validates_acceptance_of :terms



  validates_format_of :display_name, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true


  around_create :register_hook

  has_many :withdrawals
  has_many :lineups



# config/routes.rb

end

  private
    def register_hook
      self.permissions = 1
      self.balance = 250.00
      self.total_winnings = 0.00

      yield  # this makes the save happen

        balance = Balance.new(user_id: self.id, amount: 250.00)

        balance.save
    end

app/models/withdrawal.rb
class Withdrawal < ActiveRecord::Base
  belongs_to :user
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_filter :ensure_admin


  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
    @teams = Team.all
  end

  # GET /players/1/edit
  def edit
    @teams = Team.all
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    @player.live_score = 0
    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def clearscore
    @player = Player.find(params[:id])

    @player.live_score = 0.0
    @player.save

  end

  def update_individual
    @ids = params[:live_score]
    print("hello#{@ids}")
    @players = Player.update(params[:players], params[:players].values).reject { |p| p.errors.empty? }
    if @players.empty?
      flash[:notice] = "Products updated"
      redirect_to products_url
    else
      render :action => "edit_individual"
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    if @player.update(player_params)

      lps = LineupPlayer.where(player_id: @player.id)

      lps.each do |player|
        if Contest.find(Lineup.find(player.lineup_id).contest_id).paid_out == false
          calcTotalScore(Lineup.find(player.lineup_id))
        end
      end
      redirect_to players_url
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:id, :name, :team_id, :salary, :avgFP, :position, :live_score)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/lineups_helper.rb
module LineupsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/slates_helper.rb
module SlatesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.collection_select :team_id, @teams, :id, :name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.number_field :salary %>
  </div>

  <div class="field">
    <%= f.label :avgFP %><br>
    <%= f.text_field :avgFP %>
  </div>

  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>

<% if !@player.new_record? %>
  

  <div class="field">
    <%= f.label :live_score %><br>
    <%= f.number_field :live_score, :class => 'text_field', :step => 0.5 %>
  </div>
<% end %>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Team</th>
      <th>Salary</th>
      <th>Avg FP/Game</th>
      <th>Position</th>
      <th>Live Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.id %></td>
        <td><%= player.name %></td>
        <td><%= player.team_id %></td>
        <td><%= player.salary %></td>
        <td><%= player.avgFP %></td>
        <td><%= player.position %></td>
        <td><%= player.live_score %></td>
        <td><%= link_to 'Clear Score', clearscore_path(:id => player.id), :remote=>true %></td> 


        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @player.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player.team_id %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @player.salary %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>